/**
 * Export Service for Standard GIS / CAD / 3D Formats
 * Supports PLY, OBJ, XYZ, GeoJSON, and DEM Summary.
 */

function generatePly(pointCloudData) {
  const points = pointCloudData.points;
  let header = `ply\nformat ascii 1.0\ncomment Exported by AeroVista-3D SIH26158 NTRO Recon Engine\nelement vertex ${points.length}\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n`;
  
  let body = points.map(p => {
    const r = Math.floor(p.r * 255);
    const g = Math.floor(p.g * 255);
    const b = Math.floor(p.b * 255);
    return `${p.x} ${p.y} ${p.z} ${r} ${g} ${b}`;
  }).join('\n');

  return header + body;
}

function generateObj(pointCloudData) {
  const points = pointCloudData.points;
  let header = `# Wavefront OBJ generated by AeroVista-3D (SIH26158)\n# Vertices: ${points.length}\n`;
  let body = points.map(p => {
    return `v ${p.x} ${p.y} ${p.z} ${p.r.toFixed(3)} ${p.g.toFixed(3)} ${p.b.toFixed(3)}`;
  }).join('\n');
  return header + body;
}

function generateXyz(pointCloudData) {
  return pointCloudData.points.map(p => `${p.x} ${p.y} ${p.z} ${p.intensity}`).join('\n');
}

function generateDemSummary(pointCloudData, mission) {
  return {
    system: "AeroVista-3D Tactical Single-Pass DEM Generator",
    missionId: mission.id,
    missionTitle: mission.title,
    spatialReference: "WGS 84 / UTM Metric Grid",
    groundSampleDistanceMeters: mission.flightProfile.groundSampleDistanceCm / 100,
    boundingBox: pointCloudData.bounds,
    verticalAccuracyRMSE: mission.flightProfile.reconstructionAccuracyRMSE,
    totalPoints: pointCloudData.pointCount,
    rasterGridResolution: "0.25m x 0.25m per cell",
    elevationStats: {
      minElevationMeters: pointCloudData.bounds.min.z,
      maxElevationMeters: pointCloudData.bounds.max.z,
      heightSpanMeters: pointCloudData.bounds.dimensionsMeters.height
    }
  };
}

module.exports = {
  generatePly,
  generateObj,
  generateXyz,
  generateDemSummary
};
